name: neighbr
description: "A mobile platform designed to strengthen local economies by directly connecting community members with small businesses in a more dynamic and meaningful way"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  go_router: ^14.0.0
  flutter_secure_storage: ^10.0.0
  image_picker: ^1.2.1
  geolocator: ^14.0.2
  profanity_filter: ^2.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
